name: Test and Deploy on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  verify-scripts:
    name: Verify Required Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          missing=""
          for script in start build deploy test; do
            if ! jq -e --arg s "$script" '.scripts[$s]' package.json > /dev/null; then
              missing="$missing $script"
            fi
          done
          if [ -n "$missing" ]; then
            echo "❌ Missing required scripts in package.json:$missing"
            exit 1
          else
            echo "✅ All required scripts found."
          fi

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: verify-scripts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Setup Chrome (for Karma)
        uses: browser-actions/setup-chrome@v1
      - run: npm run test -- --watch=false --browsers=ChromeHeadless

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
