name: Test and Deploy on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  call-common-workflow:
    uses: ./.github/workflows/common.yml
    with:
      run-deploy: true
