name: Test and Build on Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  call-common-workflow:
    uses: ./.github/workflows/common.yml
    with:
      run-deploy: false
