name: Test and Build on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  verify-scripts:
    name: Verify Required Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          node -e "
          const pkg = require('./package.json');
          const required = ['start', 'build', 'deploy', 'test'];
          const missing = required.filter(s => !pkg.scripts || !pkg.scripts[s]);
          if (missing.length) {
            console.error('❌ Missing scripts:', missing.join(', '));
            process.exit(1);
          } else {
            console.log('✅ All required scripts found.');
          }
          "

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: verify-scripts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Install Chrome (for Karma)
        run: sudo apt-get install -y google-chrome-stable
      - run: npm run test -- --watch=false --browsers=ChromeHeadless

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
