name: Test and Build on Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify-scripts:
    uses: ./.github/workflows/verify-scripts.yml

  test:
    needs: verify-scripts
    uses: ./.github/workflows/run-tests.yml

  build:
    needs: verify-scripts
    uses: ./.github/workflows/build-project.yml

  sitemap:
    needs: verify-scripts
    uses: ./.github/workflows/create-sitemap.yml
