name: verify-scripts.yml

on:
  workflow_call

jobs:
  verify-scripts:
    name: Verify Required Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Make verify-scripts.sh executable
        run: chmod +x .github/scripts/verify-scripts.sh
      - name: Verify required scripts
        run: .github/scripts/verify-scripts.sh
